# Generated by Django 6.0.5 on 2026-05-12 07:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#667eea", max_length=7, verbose_name="Color"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Proyecto",
                "verbose_name_plural": "Categorías de Proyectos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único del proyecto (ej: PIAP-2026-001)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Proyecto"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INICIACION", "Iniciación"),
                            ("PLANIFICACION", "Planificación"),
                            ("EJECUCION", "Ejecución"),
                            ("MONITOREO", "Monitoreo y Control"),
                            ("CIERRE", "Cierre"),
                            ("PAUSADO", "Pausado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="INICIACION",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="Fecha de Inicio Planificada"),
                ),
                (
                    "planned_end_date",
                    models.DateField(verbose_name="Fecha de Fin Planificada"),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Inicio Real"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin Real"
                    ),
                ),
                (
                    "planned_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Presupuesto Planificado",
                    ),
                ),
                (
                    "actual_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Presupuesto Ejecutado",
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        help_text="Objetivos SMART del proyecto",
                        verbose_name="Objetivos del Proyecto",
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        help_text="Delimitación del alcance",
                        verbose_name="Alcance del Proyecto",
                    ),
                ),
                (
                    "deliverables",
                    models.TextField(
                        blank=True, null=True, verbose_name="Entregables Principales"
                    ),
                ),
                (
                    "identified_risks",
                    models.TextField(
                        blank=True, null=True, verbose_name="Riesgos Identificados"
                    ),
                ),
                (
                    "constraints",
                    models.TextField(
                        blank=True, null=True, verbose_name="Restricciones"
                    ),
                ),
                (
                    "assumptions",
                    models.TextField(blank=True, null=True, verbose_name="Supuestos"),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% de Completitud",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="directed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Director del Proyecto",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patrocinador",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.projectcategory",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comentario")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario del Proyecto",
                "verbose_name_plural": "Comentarios del Proyecto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Documento"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="projects/documents/", verbose_name="Archivo"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del Proyecto",
                "verbose_name_plural": "Documentos del Proyecto",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del Hito"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("planned_date", models.DateField(verbose_name="Fecha Planificada")),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Real"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completado"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hito del Proyecto",
                "verbose_name_plural": "Hitos del Proyecto",
                "ordering": ["project", "order", "planned_date"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["code"], name="projects_pr_code_80abae_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["director"], name="projects_pr_directo_30cf1d_idx"
            ),
        ),
    ]
