# Generated by Django 6.0.5 on 2026-05-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "goal",
                    models.TextField(blank=True, null=True, verbose_name="Objetivo"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Capacidad (Puntos)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEADO", "Planeado"),
                            ("ACTIVO", "Activo"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="PLANEADO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
                "ordering": ["project", "number"],
            },
        ),
        migrations.CreateModel(
            name="BacklogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "acceptance_criteria",
                    models.TextField(
                        blank=True, null=True, verbose_name="Criterios de Aceptación"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "story_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos de Historia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BACKLOG", "Backlog"),
                            ("EN_SPRINT", "En Sprint"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="BACKLOG",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden en Backlog"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlog_items",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="projects.sprint",
                        verbose_name="Sprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia de Usuario",
                "verbose_name_plural": "Historias de Usuario",
                "ordering": ["project", "order", "-priority"],
            },
        ),
    ]
