# Generated by Django 6.0.5 on 2026-05-12 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_incident_risk_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PM", "Project Manager"),
                            ("DESARROLLADOR", "Desarrollador"),
                            ("TESTER", "Tester"),
                            ("ANALISTA", "Analista"),
                            ("STAKEHOLDER", "Stakeholder"),
                        ],
                        default="DESARROLLADOR",
                        max_length=20,
                        verbose_name="Rol en Proyecto",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro del Proyecto",
                "verbose_name_plural": "Miembros del Proyecto",
                "ordering": ["project", "role", "user__first_name"],
                "unique_together": {("project", "user")},
            },
        ),
    ]
