# Generated by Django 6.0.5 on 2026-05-13 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "impact_estimated",
                    models.TextField(
                        blank=True, null=True, verbose_name="Impacto Estimado"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("EN_EVALUACION", "En Evaluación"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="SOLICITADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Decisión"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Decidido por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Cambio",
                "verbose_name_plural": "Solicitudes de Cambio",
                "ordering": ["project", "status", "-created_at"],
            },
        ),
    ]
