# Generated by Django 6.0.5 on 2026-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dirección del Cliente"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo del Cliente"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nombre de la Empresa o Cliente",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Teléfono del Cliente",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_representative",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Representante Legal o Apoderado",
            ),
        ),
    ]
