# Generated by Django 6.0.5 on 2026-05-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_client_address_project_client_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_billing_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Correo de Facturación",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_cfdi_usage",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Uso de CFDI"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_rfc",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="RFC"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_tax_regime",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Régimen Fiscal"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_zip_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Código Postal"
            ),
        ),
    ]
