# Generated by Django 6.0.5 on 2026-05-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_client_billing_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="developer_representative",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Representante Legal (Nuestra Empresa)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_manager_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Responsable del Proyecto (Nuestra Empresa)",
            ),
        ),
    ]
