# Generated by Django 6.0.5 on 2026-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_developer_representative_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Maewallis Corp",
                        max_length=255,
                        verbose_name="Nombre de la Empresa",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        default="Maewallis Corp",
                        max_length=255,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "representative_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Representante Legal",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RFC"
                    ),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Régimen Fiscal",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Fiscal"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Código Postal",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo de Contacto",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de la Empresa",
                "verbose_name_plural": "Configuraciones de la Empresa",
            },
        ),
    ]
