# Generated by Django 6.0.5 on 2026-05-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_companysettings"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE projects_projectcategory SET created_at = CURRENT_TIMESTAMP WHERE created_at < '1970-01-01' OR created_at IS NULL;",
            reverse_sql=migrations.RunSQL.noop
        )
    ]
